name: ride_booking
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 1.1.2
  http: 0.12.2
  hexcolor: 1.0.6
  pinput: 1.0.0
  geolocator: 6.2.1
  location: 3.2.4
  geocoder: 0.2.1
  flutter_markdown: 0.5.2
  curved_navigation_bar: 0.3.7
  intl_phone_number_input: 0.6.0
  google_sign_in: 4.5.9
  google_maps_flutter: 1.2.0
  cupertino_icons: ^1.0.0
  device_preview: 0.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
